### ISSUE TITLE
Skin missing at pymel.readthedocs.org

### ISSUE THREAD

**Issue by lofidevops** [LumaPictures/pymel-docs#1]
**Steps to reproduce:**
- Open http://pymel.readthedocs.org
- Open http://help.autodesk.com/cloudhelp/2016/JPN/Maya-Tech-Docs/PyMel/index.html

**What should happen:**

Both versions have a skin.

**What happens instead:**

RTD version seems to be missing its skin. Other docs on RTD are working for me.

**Comment by chadrik** [comment]
Hi @kwill.  The readthedocs documentation was an experiment that never succeeded.  Builds that took a few minutes locally were still running on readthedocs.org after almost a week, so ultimately I gave up.  I made the docs private for now and I'll take another try at getting them to build.  Thanks for the reminder!

**Comment by lofidevops** [comment]
Ok, I'll stick to the docs hosted at Autodesk. Thanks!
